version: '3.5'
services:
  jaeger-collector:
    restart: always
    image: jaegertracing/jaeger-collector
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
    #ports:
    #  - "14250:14250"
    #  - "14267:14267"
    #  - "14268:14268"
    #  - "9411:9411"
    environment:     
     - SERVICE_NAME=jaeger-collector
     - SERVICE_TAGS=apm
     - COLLECTOR_ZIPKIN_HTTP_PORT=9411
     - SPAN_STORAGE_TYPE=elasticsearch
     - ES_SERVER_URLS=http://localhost:9200
  jaeger-query:
    restart: always
    image: jaegertracing/jaeger-query
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
    ports:
      - "16686:16686/tcp"
    environment:     
     - SERVICE_NAME=jaeger-query
     - SERVICE_TAGS=apm   
     - COLLECTOR_ZIPKIN_HTTP_PORT=9411
     - SPAN_STORAGE_TYPE=elasticsearch
     - ES_SERVER_URLS=http://localhost:9200
  jaeger-agent:
    restart: always
    image: jaegertracing/jaeger-agent
    deploy:
     mode: global
     restart_policy:
      condition: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
    environment:     
     - SERVICE_NAME=jaeger-agent
     - SERVICE_TAGS=apm
    depends_on:
        - jaeger-collector
    command: ["--reporter.type=grpc", "--reporter.grpc.host-port=jaeger-collector:14250"]